version: "3.3"

services:
  frontend:
    image: intkbv/centraalmuseum-frontend:sha-d9ddf61
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    depends_on:
      - backend
    networks:
      - nw-webserver
      - backend
    ports:
      - 3000:3000
    deploy:
      replicas: 4

  backend:
    image: intkbv/centraalmuseum-backend:sha-de4c000
    environment:
      SITE: Plone
      ZEO_ADDRESS: zeo:8100
    volumes:
      - /var/local/centraalmuseum:/app/logs
      - /var/local/centraalmuseum/import/:/app/import
    networks:
      - nw-webserver
      - backend
    ports:
      - 8080:8080
    deploy:
      replicas: 4

  backend-sync:
    image: intkbv/centraalmuseum-backend:sha-de4c000
    environment:
      SITE: Plone
      ZEO_ADDRESS: zeo:8100
    volumes:
      - /var/local/centraalmuseum:/app/logs
      - /var/local/centraalmuseum/import/:/app/import
    networks:
      - nw-webserver
      - backend
    ports:
      - 8081:8080
    deploy:
      replicas: 1

  zeo:
    image: plone/plone-zeo:latest
    volumes:
      - /var/local/centraalmuseum/data:/data
    networks:
      - backend
      - nw-webserver

volumes:
  vol-traefik-public-certificates:
    driver_opts:
      type: none
      device: /data/traefik/certificates
      o: bind
  vol-traefik-config:
    driver_opts:
      type: none
      device: /data/traefik/config
      o: bind

networks:
  nw-webserver:
    external: true
    driver: overlay
  backend:
    driver: overlay
